; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:cubecell_board]
platform  = heltec-cubecell
board     = cubecell_board
framework = arduino

monitor_speed = 115200

; LoRaWAN-Optionen. Wir nutzen zwar P2P, der CubeCell-Core
; verlangt aber trotzdem eine gueltige Region fuer den Build.
board_build.arduino.lorawan.region      = EU868
board_build.arduino.lorawan.rgb         = ACTIVE
board_build.arduino.lorawan.debug_level = NONE
board_build.arduino.lorawan.at_support  = OFF

lib_deps =
    adafruit/Adafruit BME280 Library
    adafruit/Adafruit Unified Sensor




;[env:cubecell_board]
;board = cubecell_board
;framework = arduino
;monitor_speed = 115200
;build_flags =
;    -D REGION_EU868
;    -D LoraWan_RGB=1
;lib_deps =  
;    adafruit/Adafruit BME280 Library
;    adafruit/Adafruit Unified Sensor